name: NLRB_Labor_Bot

# Controls when the action will run.
on:
  schedule:
    - cron: '0 9 * * *'

jobs:
  generate-data:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          install.packages('sessioninfo')
          install.packages("tidyverse")
          install.packages('rvest')
          install.packages('janitor')
          install.packages('dplyr')
          install.packages('furrr')
          install.packages('rjson')
          install.packages('curl')
          install.packages('DBI')
          install.packages('RSQLite')
          install.packages('RCurl')
          install.packages('data.table')
          install.packages('lubridate')
          install.packages('knitr')
        shell: Rscript {0}



      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Generate data
        run: |
          source("R/some_tests.R")
        shell: Rscript {0}


      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push
