name: Python NLRB

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '10 9 * * *'

jobs:
  scrape:
    runs-on: macos-latest
    steps:

    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # Step 3: Install requirements, so Python script can run
    - name: Install requirements
      run: python -m pip install pandas zipfile csv slack slack.errors datetime
    # Step 4    
    - name: Run script to create main csv
      run: python bot.py     
    # Step 5
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
